server:
  port: 58065
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# 应用配置
app:
  system:
    name: 政企商机智能体

spring:
  profiles:
    active: dev
    #active: prod
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      separator: ;
      encoding: utf-8
  webflux:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 基础日志
logging:
  level:
    com.alibaba.cloud.ai.dataagent.service: debug
    com.alibaba.cloud.ai.dataagent.workflow.node: debug
    com.alibaba.cloud.ai.mapper: debug
