spring:
  profiles:
    active: dev
    #active: prod
  application:
    name: data-agent-scope
  autoconfigure:
    exclude:
      - io.agentscope.spring.boot.a2a.AgentscopeA2aAutoConfiguration
  datasource:
    url: ${DATA_AGENT_DATASOURCE_URL:jdbc:mysql://localhost:3306/data_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_AGENT_DATASOURCE_USERNAME:root}
    password: ${DATA_AGENT_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# DataAgentScope Web Application Configuration
server:
  port: 58064
  address: 0.0.0.0

# MyBatis 配置
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# AgentScope Configuration
agentscope:
  # DashScope API Key (set via environment variable: DASHSCOPE_API_KEY)
  #api-key: ${DASHSCOPE_API_KEY:}
  api-key: sk-26979f34a1a64da2ad4e695b5f4e9d6a
  # Model name 当前有bug只能使用这种没有版本号的模型名称qwen-max、qwen-plus、qwen-turbo
  model-name: qwen-max
  # Base URL for DashScope API (optional, default is Alibaba Cloud official endpoint)
  base-url: https://dashscope.aliyuncs.com
  # Graceful Shutdown 优雅停机
  shutdown:
    enabled: true
    timeout-seconds: 20
  # HTTP Compression HTTP 压缩
  compression:
    enabled: false

logging:
  level:
    com.alibaba.cloud.ai.datascope: DEBUG
    com.jldaren.agent.ai.datascope: DEBUG
    io.agentscope: DEBUG
    org.springframework.web.servlet.resource.ResourceHttpRequestHandler: ERROR  # 忽略静态资源找不到的警告
